# Android emulator on the dev VM, talking to the local m2dev server directly.
m2.abi=x86_64
m2.serverMode=remote
m2.serverHost=172.16.255.2
m2.authPort=11000
m2.channelPort=11011
m2.dataUrl=
m2.dataVersion=2
m2.versionName=dev
