apply plugin: 'com.android.application'

android {
    namespace "com.metin2.client"
    compileSdkVersion 33
    buildToolsVersion "33.0.1"
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "com.metin2.client"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions -Wno-invalid-source-encoding"
                arguments "-DANDROID_STL=c++_shared", "-DANDROID_TOOLCHAIN=clang"
                abiFilters 'arm64-v8a', 'x86_64'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            jniDebuggable true
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
            assets.srcDirs = ['src/main/assets']
        }
    }

    externalNativeBuild {
        cmake {
            path file("../../clientsource/CMakeLists.txt")
        }
    }

    packagingOptions {
        pickFirst 'lib/armeabi-v7a/libmetin2_mobile.so'
        pickFirst 'lib/arm64-v8a/libmetin2_mobile.so'
        pickFirst 'lib/x86/libmetin2_mobile.so'
        pickFirst 'lib/x86_64/libmetin2_mobile.so'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
